use DBRECATALOG;

insert into TBPROPERTY_CATALOG (CATALOG_ID, PROPERTY_KEY, PROPERTY_VALUE) 
	VALUES("SEGUROS", "SOURCE_LOCATION", "C:\Git_Projects\SEGUROS\R1PAB001\R1PAB0\GEMGVK01.BAS");   
    
SELECT * FROM    TBPROPERTY_CATALOG;
DELETe from TBPROPERTY_CATALOG;
    